### PR TITLE
add JSON & TypeScript-Definitions

### PR DESCRIPTION
**Pull request by MrSpoocy**
Simple add JSON from https://github.com/douglascrockford/JSON-js.

I also ask about TypeScript definition file (https://github.com/adobe-extension-tools/extendscript-es5-shim-ts/issues/1). We don't need 100 repository if everyone need the same :) Maybe i create own TS file the simple copy from https://github.com/DefinitelyTyped/DefinitelyTyped and make a pull request.

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
>Maybe i create own TS file the simple copy from DefinitelyTyped/DefinitelyTyped and make a pull request.

 PRs are always welcome

**Comment by MrSpoocy** [comment]
This is already is PR for JSON support xD You can merge it after review.

**Comment by fabianmoronzirfas** [comment]
Thank you. I’m currently not in the reach of a computer. Will be back in two weeks. Then I can do a review

**Comment by MrSpoocy** [comment]
i simple copy & past the TypeScript Definition from Microsoft but only the function from the folders (include the Apache license header). Also update the Build script & the package.json.

**Comment by lumenn** [comment]
@fabianmoronzirfas 
I'll be glad if you could check this PR, also users of extendscriptr would be able to benefit from this typescript definitions, and also JSON :)

**Comment by fabianmoronzirfas** [comment]
@lumenn Yes I will. It's on the todo pile. Sorry for the delay. 
If you are invested in this would you like to become a contributor on Extendscript org and on the Extendscrpitr repo?

**Pull request merged**
