### PR TITLE
Add Object.assign polyfill

### PR DESCRIPTION
**Pull request by andyinabox**
#3

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
Awesome!

**Comment by EugenTepin** [comment]
If i am not mistaken, **[Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)** is **ES6** standard method rather than **ES5**. So, i suppose we need **extendscript-es6-shim** for that method, and for many others, like **[Object.is()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is)**, **[Array.prototype.findIndex()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex)** etc. Or, we can try to use **Babel** for that, because ES6 is not just a new methods, but a new syntax.

**Comment by fabianmoronzirfas** [comment]
hm. You're right you should keep those separated.

**Comment by fabianmoronzirfas** [comment]
Okay. Moved it to a new repo https://github.com/ExtendScript/extendscript-es6-shim

**Pull request merged**
