### PR TITLE
add tests action

### PR DESCRIPTION
**Pull request by fabianmoronzirfas**

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
@lumenn Do you have an idea for a good automated test for these?
Maybe removing all the existing functions and patching them with a shim?
Once we have this going we can make a new release and it should be pushed to the registry once we merge #13

**Comment by lumenn** [comment]
Which functions would you remove ?
Never wrote any automated js tests before, thats some field i still have to learn.

For sure tests should be run on a real Adobe products, as ExtendScript has it's own things that JS does not.

If you could give me some points what could i check to get it working i'll be glad to work on those :)

**Comment by fabianmoronzirfas** [comment]
Well. Well won’t get a CI Server with an ExtendScript engine. That’s why I would set all functions we patch to undefined and let them use our shims. 

I’ll try to write a test for it.

**Comment by lumenn** [comment]
Seems like a good idea to me then.
Currently checking examples you've prepared, i'll try to work on it, been off for weekend.

**Pull request merged**
