### PR TITLE
Replace old shim with current from mozilla

### PR DESCRIPTION
**Pull request by fabianmoronzirfas**
I'm working on setting up automated tests and the array every seems not to work right. Replaced it with the current one from MDN and voilà

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
Same goes for `Array.filter`? They all break at 

    callback.__class__ !== "Function"

**Comment by fabianmoronzirfas** [comment]
I tested the old one in InDesign and it works.
Tested the new one and it works as well.

I'll be setting up a small testing utility we can use the write test we can run locally.

**Comment by lumenn** [comment]
> I tested the old one in InDesign and it works.
> Tested the new one and it works as well.
> 
> I'll be setting up a small testing utility we can use the write test we can run locally.

Anything i could help with?

**Comment by fabianmoronzirfas** [comment]
@lumenn See #17 

We should not mix setting up the tests with PRs like this one. I saw that `Array.every` also was updated on MDN. So either writing tests or walking through the shims and seeing if they are still up to date would both be a great help.

**Comment by EugenTepin** [comment]
@fabianmoronzirfas 

> I saw that Array.every also was updated on MDN.

It's been a long time, but it seems to me that the version of polyfills has not changed on MDN. I have changed some implementation details of polyfills, when I was working on it. `__class__` is among this edits. This is internal property which shows the actual type of the object (only Extendscript). I think it is safe to revert this polyfill to its original state. I have some thoughts about that, I will share them later.

**Comment by fabianmoronzirfas** [comment]
>  I have changed some implementation details of polyfills, when I was working on it. __class__ is among this edits. 

Ah. okay. We need to decide if we keep it that way or if we make it more ECMA compatible. Please share your thoughts when you have time to

**Comment by EugenTepin** [comment]
Ok, by initial design I plan to use this shims only in Extendscript engine, and I do not think that Adobe have changed script implementations in their products, so, please be sure that you launching this scripts in proper environment.
**\_\_class\_\_** property was used, because it gets more precise value of object type. Please, see this [link](https://github.com/EugenTepin/ps-util-is/blob/b54abbea1f2150ac79f552843ea83ec833c59cfb/index.js#L44), but this is only one rare case that I have found where **\_\_class\_\_** is better.
So, I think it is safe to replace my implementation with initial implementation from mdn. If you will decide to do that, please, also take into account **\_\_proto\_\_** value.

**Comment by fabianmoronzirfas** [comment]
Hm. Sounds more complicated then just replacing one shim. I'll close this and add a new issue.

**Pull request closed without merging**
